//
// Created by xiangweixin on 2020/6/28.
//

#ifndef FFMPEG4ANDROID_MASTER_XWXRESULT_H
#define FFMPEG4ANDROID_MASTER_XWXRESULT_H

#define READY 0;
#define UNKNOWN_ERROR -1;
#define INVALID_HANDLE -2;

#define GL_COMPILE_ERROR -1000;
#define GL_CREATE_PROGRAM_ERROR -1001;
#define GL_LINK_PROGRAM_ERROR -1002;

#define EGL_SWAP_BUFFER_ERROR -10000;
#define EGL_GET_DISPLAY_ERROR -10001;
#define EGL_INIT_ERROR -10002;
#define EGL_CHOOSE_CONFIG_ERROR -10003;
#define EGL_CREATE_CONTEXT_ERROR -10004;
#define EGL_CREATE_WINDOWSURFACE_ERROR -10005;
#define EGL_MAKE_CURRENT_ERROR -10006;

#endif //FFMPEG4ANDROID_MASTER_XWXRESULT_H
