//
// Created by xiangweixin on 2020/6/28.
//

#ifndef FFMPEG4ANDROID_MASTER_XWXRESULT_H
#define FFMPEG4ANDROID_MASTER_XWXRESULT_H

#define READY 0;
#define UNKNOWN_ERROR -1;
#define INVALID_HANDLE -2;

#define GL_COMPILE_ERROR -1000;
#define GL_CREATE_PROGRAM_ERROR -1001;
#define GL_LINK_PROGRAM_ERROR -1002;
#define GL_GEN_TEXTURE_ERROR -1003;
#define GL_GEN_FBO_ERROR -1004;
#define GL_GET_ATTRIBUTE_LOC_ERROR -1005;
#define GL_GET_UNIFORM_LOC_ERROR -1006;

#define EGL_SWAP_BUFFER_ERROR -10000;
#define EGL_GET_DISPLAY_ERROR -10001;
#define EGL_INIT_ERROR -10002;
#define EGL_CHOOSE_CONFIG_ERROR -10003;
#define EGL_CREATE_CONTEXT_ERROR -10004;
#define EGL_CREATE_WINDOWSURFACE_ERROR -10005;
#define EGL_MAKE_CURRENT_ERROR -10006;

#define FFMPEG_GUESS_FORMAT_FAILED -2000;
#define FFMPEG_ALLOC_OUTPUT_FORMAT_FAILED -2001;
#define FFMPEG_CODEC_OPEN_FAILED -2002;
#define FFMPEG_PARAMETERS_FROM_CONTEXT_FAILED -2003;
#define FFMPEG_AVIO_OPEN_FAILED -2004;
#define FFMPEG_WRITE_HEADER_FAILED -2005;
#define FFMPEG_INVALID_BUFFER -2006;
#define FFMPEG_SEND_FRAME_UNKNOWN_ERROR -2007;
#define FFMPEG_RECEIVE_PACKET_UNKNOWN_ERROR -2008;

#endif //FFMPEG4ANDROID_MASTER_XWXRESULT_H
